export const TABLE_HEADER = [
    {
        id : "select", 
        label : "",
        isSticky : "true",
    },
    {
        id : "vendors", 
        label : "Vendors",
    },
    {
        id : "status", 
        label : "Status",
    },
    {
        id : "poNum", 
        label : "PO/PI Number",
    },
    {
        id : "amount", 
        label : "Amount",
        isSorting : "true",
    },
    {
        id : "created_date", 
        label : "Created Date",
    },
    {
        id : "initiated_by", 
        label : "Initiated By",
    },
    {
        id : "linked_to", 
        label : "Linked To",
    },
];

export const INITIAL_DATA = [
    {
        tableId : 1,
        avatar : "", //add some icon
        vendors : "Siddharth",
        status : "In Draft",
        poNum : "PO-00034",
        amount : "25,000",
        created_date : "11-07-24",
        initiated_by : "Anikit Jain",
        linked_to : "Finance"
    },
    {
        tableId : 2,
        avatar : "", //add some icon
        vendors : "Nishchay",
        status : "Submitted",
        poNum : "PO-00067",
        amount : "75,000",
        created_date : "23-01-25",
        initiated_by : "Viraksh Goyal",
        linked_to : "Tech"
    },
    {
        tableId: 3,
        avatar: "👩‍💼",
        vendors: "Anjali",
        status: "Approved",
        poNum: "PO-00091",
        amount: "58,000",
        created_date: "05-03-25",
        initiated_by: "Megha Sharma",
        linked_to: "Marketing",
      },
      {
        tableId: 4,
        avatar: "🧑‍🔧",
        vendors: "Rahul",
        status: "In Draft",
        poNum: "PO-00102",
        amount: "12,000",
        created_date: "16-02-25",
        initiated_by: "Arjun Verma",
        linked_to: "Operations",
      },
      {
        tableId: 5,
        avatar: "👩‍💻",
        vendors: "Snigdha",
        status: "Submitted",
        poNum: "PO-00135",
        amount: "91,000",
        created_date: "10-01-25",
        initiated_by: "Rohit Gupta",
        linked_to: "HR",
      },
      {
        tableId: 6,
        avatar: "🧑‍💼",
        vendors: "Aditya",
        status: "Approved",
        poNum: "PO-00176",
        amount: "65,000",
        created_date: "20-04-25",
        initiated_by: "Tarun Singh",
        linked_to: "Tech",
      },
      {
        tableId: 7,
        avatar: "👨‍🔧",
        vendors: "Manish",
        status: "Rejected",
        poNum: "PO-00211",
        amount: "8,500",
        created_date: "02-05-24",
        initiated_by: "Kritika Yadav",
        linked_to: "Procurement",
      },
      {
        tableId: 8,
        avatar: "👩‍💼",
        vendors: "Priya",
        status: "In Draft",
        poNum: "PO-00242",
        amount: "39,000",
        created_date: "27-03-25",
        initiated_by: "Pooja Mehta",
        linked_to: "Finance",
      },
      {
        tableId: 9,
        avatar: "👨‍💻",
        vendors: "Karan",
        status: "Submitted",
        poNum: "PO-00280",
        amount: "55,500",
        created_date: "04-04-25",
        initiated_by: "Sarthak Anand",
        linked_to: "Engineering",
      },
      {
        tableId: 10,
        avatar: "👨‍💼",
        vendors: "Yash",
        status: "Approved",
        poNum: "PO-00310",
        amount: "77,000",
        created_date: "01-02-25",
        initiated_by: "Rhea Kapoor",
        linked_to: "Sales",
      },
      {
        tableId: 11,
        avatar: "👩‍🔧",
        vendors: "Divya",
        status: "Submitted",
        poNum: "PO-00349",
        amount: "44,000",
        created_date: "06-03-25",
        initiated_by: "Ankit Rao",
        linked_to: "Tech",
      },
      {
        tableId: 12,
        avatar: "👨‍💼",
        vendors: "Ravi",
        status: "In Draft",
        poNum: "PO-00380",
        amount: "33,300",
        created_date: "11-02-25",
        initiated_by: "Deepa Singh",
        linked_to: "Marketing",
      },
      {
        tableId: 13,
        avatar: "👩‍💻",
        vendors: "Neha",
        status: "Submitted",
        poNum: "PO-00414",
        amount: "22,500",
        created_date: "19-01-25",
        initiated_by: "Prateek Jain",
        linked_to: "Design",
      },
      {
        tableId: 14,
        avatar: "🧑‍🔧",
        vendors: "Tanmay",
        status: "Approved",
        poNum: "PO-00457",
        amount: "59,900",
        created_date: "03-03-25",
        initiated_by: "Gaurav Joshi",
        linked_to: "Tech",
      },
      {
        tableId: 15,
        avatar: "👨‍💼",
        vendors: "Aman",
        status: "In Draft",
        poNum: "PO-00488",
        amount: "68,000",
        created_date: "12-04-25",
        initiated_by: "Ishita Bansal",
        linked_to: "Finance",
      },
      {
        tableId: 16,
        avatar: "👩‍🔧",
        vendors: "Kriti",
        status: "Rejected",
        poNum: "PO-00512",
        amount: "13,700",
        created_date: "22-02-25",
        initiated_by: "Mukul Ahuja",
        linked_to: "Procurement",
      },
      {
        tableId: 17,
        avatar: "👨‍💻",
        vendors: "Suresh",
        status: "Submitted",
        poNum: "PO-00539",
        amount: "81,000",
        created_date: "18-03-25",
        initiated_by: "Tina Malhotra",
        linked_to: "Legal",
      },
      {
        tableId: 18,
        avatar: "👩‍💼",
        vendors: "Ritika",
        status: "Approved",
        poNum: "PO-00578",
        amount: "36,000",
        created_date: "15-01-25",
        initiated_by: "Naman Desai",
        linked_to: "HR",
      },
      {
        tableId: 19,
        avatar: "🧑‍🔧",
        vendors: "Dev",
        status: "In Draft",
        poNum: "PO-00609",
        amount: "19,500",
        created_date: "05-02-25",
        initiated_by: "Kavya Menon",
        linked_to: "Tech",
      },
      {
        tableId: 20,
        avatar: "👩‍💻",
        vendors: "Isha",
        status: "Submitted",
        poNum: "PO-00630",
        amount: "72,000",
        created_date: "08-04-25",
        initiated_by: "Rajat Bhatt",
        linked_to: "Marketing",
      },
      {
        tableId: 21,
        avatar: "👨‍💼",
        vendors: "Rohan",
        status: "Approved",
        poNum: "PO-00667",
        amount: "88,800",
        created_date: "27-03-25",
        initiated_by: "Zara Sheikh",
        linked_to: "Finance",
      },
      {
        tableId: 22,
        avatar: "🧑‍💼",
        vendors: "Vikram",
        status: "In Draft",
        poNum: "PO-00692",
        amount: "60,000",
        created_date: "13-01-25",
        initiated_by: "Reena Arora",
        linked_to: "Tech",
      },
      {
        tableId: 23,
        avatar: "👨‍💻",
        vendors: "Mohit",
        status: "Submitted",
        poNum: "PO-00715",
        amount: "24,400",
        created_date: "17-04-25",
        initiated_by: "Sakshi Roy",
        linked_to: "Design",
      },
      {
        tableId: 24,
        avatar: "👩‍🔧",
        vendors: "Tanya",
        status: "Rejected",
        poNum: "PO-00744",
        amount: "14,200",
        created_date: "09-03-25",
        initiated_by: "Varun Reddy",
        linked_to: "Procurement",
      },
      {
        tableId: 25,
        avatar: "🧑‍💼",
        vendors: "Harsh",
        status: "Approved",
        poNum: "PO-00779",
        amount: "47,000",
        created_date: "01-02-25",
        initiated_by: "Karan Luthra",
        linked_to: "Legal",
      }
]
